[package]
name = "svd_reader"
version = "0.1.0"
authors = ["WRR"]
edition = "2018"

[dependencies]
svd-parser = { version = "0.7.0", path = "../svd", features = [ "serde_svd" ] }
#serde = { version = "1.0", features = [ "derive" ] } 
serde_json = "1.0"
